[package]
name = "hello_world"
version = "0.0.1"
upgrade_policy = "compatible"

[addresses]
hello_world = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }