[package]
name = "c1"
version = "17.0.0"

[addresses]
c1 = "0x61dbdabc048aa3b85609e916624f46597ff9ada018a57824cd9eb5dcebe931f5"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "918b643c98f81b8b2b3dd3a597329210b35c30b3" }